server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    #path: /swagger-ui.html
    #disable-swagger-default-url: true
    display-request-duration: true
    groups-order: DESC
    apisSorter: alpha
    operationsSorter: method
    tagsSorter: alpha
  #show-actuator: true
  group-configs:
    - group: demo
      paths-to-match: /demo/**

